name: VisibleClimate
favicon: null
layout_spectrum: 1
typography_spectrum: 0.66108
title: Visible Climate
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-70816669-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfefa'
    - '#649b7f'
    - '#001102'
    - '#395c4b'
    - '#e9551a'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
