name: VisibleClimate
favicon: null
layout_spectrum: 1
typography_spectrum: 0.66108
title: Visible Climate
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-70816669-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.3581194595899433
  lightness: 0.875
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
