name: VisibleClimate
favicon: null
layout_spectrum: 0.9947138277348131
typography_spectrum: 0.9513966275844723
title: Visible Climate
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-70816669-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.3581194595899433
  lightness: 0.8261263254098594
  saturation: 0.176213193917647
  rhythmicContrast: 0.9032140951603651
purpose: []
